### ISSUE TITLE
Background image not responsive?

### ISSUE THREAD

**Issue by robinleung** [moodleou/moodle-qtype_ddmarker#26]
Hello,

I'm not sure if this is an issue that's been fixed in recent versions. But I had a report that when an instructor is previewing a question the drop zones are unreachable because it runs off the screen because the user is using a non-widescreen. 

I'm running ddmarker 1.4 in latest version of Moodle 2.8.

![2015-03-03_16-11-59](https://cloud.githubusercontent.com/assets/8377859/6475546/59ce150a-c1c0-11e4-84e1-fae7ac8023ac.png)

**Comment by timhunt** [comment]
You are not using the latest version of this plugin. The overlapping drag items bug has been fixed.

The background image size is limited to being 600px wide (https://github.com/moodleou/moodle-qtype_ddmarker/blob/master/questiontype.php#L32). If images that wide do not fit in your theme, well, there are probably two choices:

1. Use a different theme.
2. Use a smaller background image so that it does fit in your theme.
3. (Since I note that your screen-grab is from the question preview pop-up) re-size the pop-up to be bigger.

**Comment by robinleung** [comment]
Thanks Tim. Will update the plugin and test.
